package utils.corbaInterface;


/**
* corbaInterface/IDCRS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./IDCRS.idl
* Wednesday, October 24, 2018 11:11:41 PM EDT
*/

public interface IDCRS extends IDCRSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IDCRS
