package utils.corbaInterface;


/**
* corbaInterface/IDCRSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./IDCRS.idl
* Wednesday, October 24, 2018 11:11:41 PM EDT
*/

public interface IDCRSOperations 
{

  /* Advisor Operations */
  boolean addCourse (String advisorId, String courseId, String semester, int capacity);
  boolean removeCourse (String advisorId, String courseId, String semester);
  org.omg.CORBA.Any listCourseAvailability (String advisorId, String semester);

  /* Student Operations */
  org.omg.CORBA.Any enrolCourse (String studentId, String courseId, String semester);
  org.omg.CORBA.Any getClassSchedule (String studentId);
  boolean dropCourse (String studentId, String courseId);
  org.omg.CORBA.Any swapCourse (String studentId, String newCourseId, String oldCourseId);
} // interface IDCRSOperations
