package utils.corbaInterface;

/**
* corbaInterface/IDCRSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./IDCRS.idl
* Wednesday, October 24, 2018 11:11:41 PM EDT
*/

public final class IDCRSHolder implements org.omg.CORBA.portable.Streamable
{
  public utils.corbaInterface.IDCRS value = null;

  public IDCRSHolder ()
  {
  }

  public IDCRSHolder (utils.corbaInterface.IDCRS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = utils.corbaInterface.IDCRSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
	  utils.corbaInterface.IDCRSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return utils.corbaInterface.IDCRSHelper.type ();
  }

}
